### ISSUE TITLE
Input log file from somewhere

### ISSUE THREAD

**Issue by montao** [Sanjivani-S/DraftGPT#15]
it should be possible to use a log file so that GPT can look in a large log file for an error message that could be informative, for example https://raw.githubusercontent.com/logpai/loghub/master/Linux/Linux_2k.log

**Comment by montao** [comment]
include error message from TLS error

**Comment by Sanjivani-S** [comment]
Log file can be given as input from github actions, as shown in image below.
If Log file is not found, it raises an error.
If Slack channel input is found along with log file input, log file input is appended to slack channel input.

![image](https://github.com/Sanjivani-S/DraftGPT/assets/60509878/e7aa20fc-2dfa-4164-8587-dd296cd97ea5)
